# Generated by Django 5.1.7 on 2025-11-05 14:26

import django.db.models.deletion
import secretaria.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], unique=True)),
            ],
            options={
                'verbose_name': 'Bimestre',
                'verbose_name_plural': 'Bimestres',
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Entrega de Trabalho'), ('feriado', 'Feriado'), ('evento', 'Evento')], max_length=10)),
            ],
            options={
                'verbose_name': 'Evento do calendário',
                'verbose_name_plural': 'Eventos do calendário',
            },
        ),
        migrations.CreateModel(
            name='EventoExtracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('professor_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Evento extracurricular',
                'verbose_name_plural': 'Eventos extracurriculares',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('exemplares_disponiveis', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sala')),
                ('tipo', models.CharField(choices=[('SALA', 'Sala de Aula'), ('LAB', 'Laboratório'), ('QUADRA', 'Quadra/Espaço Esportivo')], default='SALA', max_length=10)),
                ('capacidade', models.IntegerField(default=30)),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos (Ex: Projetor, 30 PCs)')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_aluno', models.CharField(max_length=50, verbose_name='Digite o nome do Aluno')),
                ('phone_number_aluno', models.CharField(max_length=11, validators=[secretaria.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx')),
                ('email_aluno', models.EmailField(max_length=100, verbose_name='Digite o email do aluno')),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, verbose_name='Digite o cpf do aluno')),
                ('birthday_aluno', models.DateField(verbose_name='Data de nascimento')),
                ('ativo', models.BooleanField(default=True)),
                ('class_choice', models.CharField(blank=True, choices=[('1A', '1 ANO A'), ('1B', '1 ANO B'), ('1C', '1 ANO C'), ('2A', '2 ANO A'), ('2B', '2 ANO B'), ('2C', '2 ANO C'), ('3A', '3 ANO A'), ('3B', '3 ANO B'), ('3C', '3 ANO C')], max_length=2, verbose_name='Turma')),
                ('month_choice', models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, verbose_name='Mês da matrícula')),
                ('faltas_aluno', models.PositiveIntegerField(default=0, verbose_name='Número de Faltas')),
                ('presencas_aluno', models.PositiveIntegerField(default=0, verbose_name='Número de Presenças')),
                ('ano_letivo', models.PositiveIntegerField(default=2025, verbose_name='Ano Letivo')),
                ('comentario_descritivo', models.TextField(blank=True, null=True, verbose_name='Comentário Descritivo do Aluno/Performance')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da advertência')),
                ('motivo', models.CharField(choices=[('FJI', '-Faltas injustificadas'), ('DSP', '-Desrespeito a colegas ou professores'), ('CEL', '-Uso de celular sem autorização'), ('RGR', '-Descumprimento das regras da escola'), ('AGV', '-Agressões verbais'), ('DPM', '-Dano leve ao patrimônio escolar'), ('DOB', '-Desobediência a orientações'), ('IND', '-Atos de indisciplina em sala'), ('UNI', '-Uso inadequado do uniforme'), ('CPM', '-Comportamento impróprio no ambiente escolar'), ('LGF', '-Uso de linguagem ofensiva'), ('FRA', '-Cola ou fraude em avaliações'), ('BLG', '-Bullying ou assédio'), ('OUTROS', '-Outros motivos')], max_length=255, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
            ],
            options={
                'verbose_name': 'Advertência',
                'verbose_name_plural': 'Advertências',
            },
        ),
        migrations.CreateModel(
            name='AtividadePendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluida', 'Concluída')], default='Pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
            ],
            options={
                'verbose_name': 'Atividade Pendente',
                'verbose_name_plural': 'Atividades Pendentes',
                'ordering': ['data_limite'],
            },
        ),
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('computador', 'Computador')], default='livro', max_length=20)),
                ('computador', models.CharField(blank=True, help_text='Identificação do computador', max_length=100, null=True)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaria.livro')),
            ],
            options={
                'verbose_name': 'Empréstimo de Livro ou Computador',
                'verbose_name_plural': 'Empréstimos de Livros ou Computadores',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('disciplina', models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Itinerário técnico')], max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.bimestre')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Itinerário técnico')], max_length=4, verbose_name='Disciplina Principal')),
                ('name_professor', models.CharField(max_length=50, verbose_name='Digite o nome do professor')),
                ('phone_number_professor', models.CharField(max_length=11, validators=[secretaria.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx')),
                ('email_professor', models.EmailField(max_length=100, verbose_name='Digite o email do professor')),
                ('cpf_professor', models.CharField(max_length=11, unique=True, verbose_name='Digite o cpf do professor')),
                ('birthday_professor', models.DateField(verbose_name='Data de nascimento')),
                ('matricula_professor', models.CharField(max_length=11, unique=True, verbose_name='Digite sua matricula: ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Digite o nome do responsavel')),
                ('phone_number', models.CharField(max_length=11, validators=[secretaria.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Digite o email do responsavel')),
                ('adress', models.CharField(max_length=100, verbose_name='Digite o endereço do responsavel')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[secretaria.validators.validar_cpf], verbose_name='Digite o cpf do responsavel')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='Responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.responsavel'),
        ),
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início da suspensão')),
                ('data_fim', models.DateField(verbose_name='Fim da suspensão')),
                ('motivo', models.CharField(choices=[('AGF', '-Agressão física a colegas ou funcionários'), ('AME', '-Ameaças verbais ou físicas'), ('BLG-R', '-Bullying recorrente ou grave'), ('DSP-G', '-Desrespeito grave à autoridade escolar'), ('VDM', '-Vandalismo / dano intencional ao patrimônio'), ('SUB', '-Uso ou posse de substâncias proibidas'), ('REC', '-Reincidência em comportamentos advertidos'), ('IMP', '-Divulgação de conteúdo impróprio'), ('RFT', '-Roubo ou furto na escola'), ('BRG', '-Participação em brigas ou tumultos graves'), ('RSC', '-Comportamento de risco à integridade física'), ('PRG', '-Porte de armas ou objetos perigosos'), ('FAL', '-Falsificação de documentos ou assinaturas'), ('RES', '-Desrespeito extremo em ambiente escolar'), ('SEG', '-Violação grave de normas de segurança')], max_length=255, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
            ],
            options={
                'verbose_name': 'Suspensão',
                'verbose_name_plural': 'Suspensões',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('1A', '1 ANO A'), ('1B', '1 ANO B'), ('1C', '1 ANO C'), ('2A', '2 ANO A'), ('2B', '2 ANO B'), ('2C', '2 ANO C'), ('3A', '3 ANO A'), ('3B', '3 ANO B'), ('3C', '3 ANO C')], max_length=2, verbose_name='Turma')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='Dia da Semana')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Programado')),
                ('atividades', models.TextField(blank=True, verbose_name='Atividades Previstas')),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos Necessários')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.professor', verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Planejamento Semanal',
                'verbose_name_plural': 'Planejamentos Semanais',
                'ordering': ['data_aula', 'horario_inicio'],
                'unique_together': {('turma', 'data_aula', 'horario_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('finalidade', models.CharField(max_length=255, verbose_name='Finalidade da Reserva')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.professor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.sala')),
            ],
            options={
                'verbose_name': 'Reserva de Sala',
                'verbose_name_plural': 'Reservas de Salas',
                'unique_together': {('sala', 'data', 'horario_inicio')},
            },
        ),
    ]
