# Generated by Django 5.1.7 on 2025-11-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_nota', to='secretaria.nota'),
        ),
    ]
