# Generated by Django 5.1.7 on 2025-11-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_aluno_aluno_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamentosemanal',
            options={'ordering': ['data_aula'], 'verbose_name': 'Planejamento Semanal', 'verbose_name_plural': 'Planejamentos Semanais'},
        ),
        migrations.AlterUniqueTogether(
            name='planejamentosemanal',
            unique_together={('turma', 'data_aula')},
        ),
        migrations.RemoveField(
            model_name='planejamentosemanal',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='planejamentosemanal',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='planejamentosemanal',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='planejamentosemanal',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='planejamentosemanal',
            name='turno',
        ),
    ]
